<html>

<head>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.css">
	<link href="https://fonts.googleapis.com/css?family=Encode+Sans|Julius+Sans+One|Open+Sans|Rosario|Tajawal|Wire+One" rel="stylesheet">
	<link rel="stylesheet" href="../views/css/animation.css">

</head>

<body>
		
	<main>
		<div id="charlotteAlain">
			<div class="charlotte">
				<span class="charlotte">Charlotte</span>
			</div> 
			
			<div class="logo" id="anim">
				<img src="../views/img/logo/logo_CA.png" alt="logo">
			</div>

			<div class="alain">
				<span class="alain">Alain</span>
			</div>
		</div>

	</main>	
	<footer>
	
	</footer>
</body>
</html>