<?php 
include 'header.phtml'; 
?>

<main>
	<section id="aPropos">
		<img src="../views/img/charlotte.jpg" alt="CharlotteAlain">
		<h1>Charlotte Alain</h1>
		<article>
			<p>Tout à commencé à mon plus jeune âge, avec le dessin. Je passais mon temps à gribouiller toutes sortes de choses, allant des dessins de portraits à des maisons, des paysages, j'adorais ça.</p>

			<p>J'ai alors affiné cette passion en prenant des cours de dessin pendant 5 ans afin d'apprendre les bases des volumes, des proportions, pour pouvoir exprimer ma créativité.</p>

			<p>Après avoir passé mon Baccalauréat scientifique, c'est tout naturellement que je me suis orientée vers une école de Design. La première année était générale. J'ai appris les bases du design produit, multimédia et espace. C'est le Design d'Espace qui m'a conquis.</p>

			<p>J'ai alors obtenu mon BTS à LISAA Nantes ( l'Institut Supérieur en Arts Appliqués), puis perfectionné ma maîtrise des logiciels de conception et de 3D photo-réalistes à Arinfo Nantes.</p>

			<p>Suite à cela j'ai intégré différents postes en entreprises en tant qu'assistante de conception et dessinatrice. J'ai travaillé sur des projets variés allant de mise en scène pour des expositions en scénographie, à la création et rénovation de bâtiments et maisons pour les particuliers et les professionnels.</p>

			<p>Ma créativité et mes connaissances techniques sont des atouts que je mettrai à votre service pour optimiser vos espaces et leur donner la grandeur dont vous rêvez.</p>
		</article>
 	</section>
</main>

<?php 
include 'footer.phtml'; 
?>