<?php 
include 'header.phtml'; 
?>

<main>

<form action="contact2.php" method="post">				    
  <?php if ($mail) : echo $messageenvoi; ?>
      <?php else : echo $messagenonenvoi; ?>

       <fieldset>
     
       


      <p>Quelques mots avant notre entretien ?</p>
      <label for="nom">/Nom : </label>
      <input type="text" name="nom" id="nom" value="<?php echo $nom ?>"><?php echo $erreurnom ?>
     <label for="prenom">/Prénom : </label>
     <input type="text" name="prenom" id="prenom" value="<?php echo $prenom ?>"><br>					
     <label for="email">/Email: </label>
     <input type="email" name="email" id="email" value="<?php echo $email ?>"><?php echo $erreuremail ?>
     <label>/Message :</label>
     <textarea name="message" ><?php echo $message ?></textarea><?php echo $erreurmessage ?>
     <input class="bouton" type="submit" name="submit" value="Envoyer" />
     <input class="bouton" type="reset" value="Annuler"/>
  <?php endif; ?>
   </fieldset>
</form>

</main>

<?php 
include 'footer.phtml'; 
?>