<?php 
include 'header.phtml'; 
?>

<main class="container">

<form method="post" action="contact.php" id="formContact">
	 
<?php if (!empty($_POST['submit'])): echo $messageenvoi ;?>

<?php endif; ?>


	<fieldset>
		<legend><i class="fa fa-envelope"></i> Contact </legend>
		<ul>
			<li class="register">
				<label for="civility">Civilité : </label>
				<select name="civility" id="civility" value="<?php echo $civility ?>">
					<option> </option>
					<option value="madame">Madame</option>
					<option value="monsieur">Monsieur</option>
					
				</select>
			
			</li>
			<li class="register">
				<label for="lastname">Nom*: </label>
				<input type="text" name="lastname" id="lastname" value="<?php echo $nom ?>"><?php echo $erreurnom ?>
			
			</li>
			<li class="register">
				<label for="firstname">Prénom: </label>
				<input type="text" name="firstname" id="firstname"  value="<?php echo $prenom ?>">
			</li>
			<li class="register">
				<label for="tel">Tel*: </label>
				<input type="text" name="tel" id="tel" value="<?php echo $tel ?>"><?php echo $erreurtel ?>
			</li>
			<li class="register">
				<label for="email">Email*: </label>
				<input type="text" name="email" id="email"value="<?php echo $email ?>"><?php echo $erreuremail ?>
			</li>
			<li class="register">
				<label for="messageCA">Votre Message*: </label>
				<textarea name="messageCA" id="messageCA" cols="20" rows="15"
				></textarea><?php echo $erreurmessageCA ?>
			</li>
			<li><input style="display:none;" type="text" id="test1" name="test1" value="hello"></li>

			<li><input style="display:none;" type="text" id="test2" name="test2" value=""></li>

			<li><input style="display:none;" type="text" id="email2" name="email2" value=""></li>
		</ul>
	</fieldset>
	
	<input class="button " type="submit" name="submit" value="Envoyer">
	<input class="button button-cancel" type="reset" value="Annuler"/>
		

</form>
<p>*:obligatoire</p>
<section>
	<h3>Me contacter par mail ou par téléphone :</h3>

	<article class="mailTel">
		<a href="mailto:charlotte_alain@hotmail.com">charlotte_alain@hotmail.com</a> 
	</article>
	<article class="mailTel">
		<a href="tel:+33661773219">06 61 77 32 19</a>
	</article>
</section>
</main>
	
<?php 
include 'footer.phtml'; 
?>