<?php 
include 'header.phtml'; 
?>

<main>

<form method="post" action="processContact.php">
	<fieldset>
		<legend><i class="fa fa-envelope"></i> Contact </legend>
		<ul>
			<li class="register">
				<label for="civility">Civilité : </label>
				<select name="civility" id="civility">
					<option></option>
					<option value="madame">Madame</option>
					<option value="monsieur">Monsieur</option>
					
				</select>
			
			</li>
			<li class="register">
				<label for="lastname">Nom : </label>
				<input type="text" name="lastname" id="lastname">
			
			</li>
			<li class="register">
				<label for="firstname">Prénom : </label>
				<input type="text" name="firstname" id="firstname">
			</li>
			<li class="register">
				<label for="tel">Tel : </label>
				<input type="text" name="tel" id="tel">
			</li>
			<li class="register">
				<label for="email">Email : </label>
				<input type="text" name="email" id="email">
			</li>
			<li class="register">
				<label for="message">Votre Message : </label>
				<textarea name="message" id="message" cols="20" rows="15"
				></textarea>
			</li>

		</ul>

	</fieldset>
	<input class="button button-primary" type="submit" value="Envoyer">
	<a class="button button-cancel small" href="contact.php">Annuler</a>
		
</form>
<p>Me contacter par mail ou par téléphone :</p>
<a href="mailto:charlotte_alain@hotmail.com">charlotte_alain@hotmail.com</a> 

<a href="tel:+33661773219">06 61 77 32 19</a>
	
</main>

<?php 
include 'footer.phtml'; 
?>