<footer id="licence" class="container">
	<p>Suivez mon actualité sur :</p>
	<div class="socialNetwork">
		<!-- <div id="twitter">
			<a href="#">
				<i class="fab fa-twitter-square"></i>
			</a>
		</div> -->
		<div id="linkedin">
			<a href="https://fr.linkedin.com/in/charlotte-alain-452a08b2">
				<i class="fab fa-linkedin"></i>
			</a>
		</div>
		<div id="facebook">
			<a href="https://www.facebook.com/architecturedinterieurCA/">
				<i class="fab fa-facebook-square"></i>
			</a>
		</div>
	</div>
		
	<div class="rightReserved">	
		<p>© Copyright 2019 <a href="https://www.architecturedinterieur-ca.com/">- www.architecturedinterieur-ca.com</a>
		</p>
		<p>	<a href="mentionsLegales.php">Mentions Légales</a></p>
		<p>
		All right reserved
		</p>
	</div>


</footer>


</body>
</html>