<footer id="licence" class="container">
	<p>Suivez mon actualité sur :</p>
	<div class="socialNetwork">
		<!-- <div id="twitter">
			<a href="#">
				<i class="fab fa-twitter-square"></i>
			</a>
		</div> -->
		<div id="linkedin">
			<a href="https://fr.linkedin.com/in/charlotte-alain-452a08b2">
				<i class="fab fa-linkedin"></i>
			</a>
		</div>
		<div id="facebook">
			<a href="https://www.facebook.com/architecturedinterieurCA/">
				<i class="fab fa-facebook-square"></i>
			</a>
		</div>
	</div>
		
	<div class="rightReserved">	
		<p>© Copyright 2019 <a href="https://architecturedinterieur-ca.com/">- https://architecturedinterieur-ca.com</a>
		</p>
		<p>	<a href="mentionsLegales.php">Mentions Légales</a></p>
		<p>
		All right reserved
		</p>
	</div>


</footer>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="../views/js/main.js"> </script>
</body>
</html>