<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
		
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css?family=Encode+Sans|Julius+Sans+One|Open+Sans|Rosario|Tajawal|Wire+One|Shadows+Into+Light" rel="stylesheet">

		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.css">

	
		<link rel="stylesheet" href="../views/css/main.css">

		<link rel="stylesheet" href="../views/js/vendor/flexslider/flexslider.css" type="text/css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>

		<title>Architecte d'intérieur Nantes, Charlotte Alain </title>
	</head>
	<body>
		<header>
			<div class="containerHeader">	
				<div id="index">
					<a href="../index.php">
			
						<div class="logo">
							<img src="../views/img/logo/logo_CA.png" alt="logo">
						</div>
								
					</a>
				</div>
				<nav>
					<ul id="drop_down_menu">
						<li><a href="prestations.php">Prestations</a></li><!--
					 --><li><a href="realisations.php">Réalisations</a>
							<ul>
								<li><a href="realisationsParticuliers.php"> Particuliers </a></li>
								<li><a href="realisationsProfessionnels.php">Professionnels </a></li>
							</ul>
						</li><!--
					 --><li><a href="aPropos.php">A propos</a></li><!--
					 --><li><a href="contact.php">Contact</a></li>
					</ul>
				</nav>
			</div>
			
		</header>