<?php 
include 'header.phtml'; ?>
<main>
	<div class="flexslider">
  <ul class="slides">
    <li>
      <img class="imgSlider" src="../views/img/slider/bt2.jpg" />
    </li>
    <li>
      <img class="imgSlider" src="../views/img/slider/bs.jpg" />
    </li>
    <li>
      <img class="imgSlider" src="../views/img/slider/bs3.jpg" />
    </li>
    <li>
      <img class="imgSlider" src="../views/img/slider/bs2.jpg" />
    </li>
    <li>
      <img class="imgSlider" src="../views/img/slider/vue2.jpg" />
    </li>
    <li>
      <img class="imgSlider" src="../views/img/slider/bt3.jpg" />
    </li>
  </ul>
</div>

</main>
<?php
include 'footer.phtml';