<?php 
include 'header.phtml'; ?>
<main>
	
     <!--  <h2 id="down"> <i class="fas fa-arrow-down"></i> Barre d'outils</h2>
      
      <div id="barreOutils">
        <h2 id="right"> <i class="fas fa-arrow-right"></i> Barre d'outils</h2>


        <button id="backward"><i class="fas fa-backward"></i></i></button>
        <button id="play"><i class="fas fa-play"></i></button>
        <button id="pause"><i class="fas fa-pause"></i></button>
        <button id="forward"><i class="fas fa-forward"></i></button>
        <button id="random"><i class="fas fa-random"></i></button>
      </div>
 -->
      <div id="carrousel">
<!-- 
          <ul>
              <li> -->
                <!-- <figure class="imgTxt"> -->
                  <img>
              <!-- <figcaption></figcaption> -->
            <!-- </figure> 
          </li>

          </ul>
 -->
      </div>
      
    </main>
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="../views/js/dataCarrousel.js"> </script>
    <script src="../views/js/functionsCarrousel.js"> </script>
    <script src="../views/js/mainCarrousel.js"> </script>


<?php
include 'footer.phtml';