<?php 
include 'header.phtml'; ?>
<main>
	<iframe src="animation.php" width="100%" height="100%" name="myFrame" id="myFrame" onload="trigger();"></iframe>
	<p>
	Jquery semble tout indiqué (ou tout autre librairie JS) pour faire ce que tu souhaite.

	Côté accessibilité, en fait c'est tout à fait faisable.

	Tu écris avec document.write une div qui cache tout le site et une autre qui contient l'animation en question.

	Si JS désactivé, tu es directement sur le site (pas de redirection donc, juste faire mumuse avec Jquery Smiley cligne )
	</p>
	<a href="animation.php">animation</a>
</main>
<?php
include 'footer.phtml';