<?php 
include 'header.phtml'; 
?>

<main class="container">
<section>
	<h4>Mentions légales</h4>
	<br>
	<article>
		<h5> Présentation générale	</h5>
		<p>Charlotte ALAIN</p>
		<p>1 rue Raspail - 44100 NANTES</p>
		<p><a href="tel:+33661773219">06 61 77 32 19</a></p>
		<p><a href="mailto:charlotte_alain@hotmail.com">charlotte_alain@hotmail.com</a> </p>
		<p>Pour toute remarque sur le fonctionnement du site, contactez Charlotte Alain.</p>
		
	</article>
	<br>
	<article>
		<h5>Hébergement </h5>
		<p> Le site est hébergé par la société OVH</p>
		<p> Siège social : 2 rue Kellermann - 59100 Roubaix - France </p>
		<p> Tel : 1007 </p>
	</article>
	<br>
	<article>
		<h5>Informations techniques </h5>
		<p>Le secret des correspondances n’est pas garanti sur le web . Il appartient à chaque utilisateur d'Internet de prendre toutes les mesures appropriées de façon à protéger ses propres données et/ou logiciels de la contamination d’éventuels virus circulant sur Internet.</p>
	</article>
	<br>
	<article>
		<h5>Droit d'auteur - Copyright </h5>
		<p>L'ensemble de ce site relève de la législation française et internationale sur le droit d'auteur et la propriété intellectuelle. </p>
		<p>Tous les droits de reproduction sont réservés, y compris pour les textes, documents téléchargeables et les représentations iconographiques et photographiques.</p>
		<p>La reproduction de tout ou partie de ce site sur un support électronique quel qu'il soit est formellement interdite sauf autorisation expresse du directeur de la publication.</p>
	</article>
	<br>
	<article>
		<h5>Crédit photo </h5>
		<p>Romain Gautron : <a href="http://www.romainlephotographe.com/fr/accueil.html">romainlephotographe.com</a>  </p>
	</article>
</section>

</main>

<?php 
include 'footer.phtml'; 
?>