<?php 
include 'header.phtml'; 
?>
<main class="container">
	<div class="photosPrestations">
		<img src="../views/img/DSC03674.jpg" class="imgPrestations" alt="">
		<img src="../views/img/ACCamera_3.jpg" class="imgPrestations" alt="">
		<img src="../views/img/DSC01682.jpg" class="imgPrestations" alt="">
		<img src="../views/img/bourdet.jpg" class="imgPrestations" alt="">
	</div>
	<section>
		<h1>ARCHITECTURE D’INTERIEUR & ARCHITECTURE COMMERCIALE</h1>
		<article>
			<h3>1ère étape - RDV conseils</h3>
			
			<p>
				A l’occasion d’une première rencontre, l’architecte d’intérieur est à votre écoute pour comprendre votre projet d’aménagement, de rénovation ou de construction. Il tient compte, non seulement de vos besoins en termes d'espaces, mais également de vos goûts (matériaux, couleurs, mobilier).
			</p>
			<p>La visite de votre logement lui permet d’évaluer le potentiel de votre intérieur et d’optimiser la surface disponible en fonction de vos besoins et votre budget.
			</p>
			<p>Son expérience et son expertise en architecture d’intérieur lui permettent de vous faire part de ses idées et de ses conseils en matière d’aménagement, de matériaux, d’équipement et d’ameublement.  
			</p>
		</article>
		<article>
			<h3>2ème étape - Etude de votre projet d’architecture d’intérieur</h3>
			<p>A partir du relevé de l’existant et du potentiel de votre intérieur, l’architecte d’intérieur vous fait différentes propositions d’aménagement de votre intérieur, à l’aide d’esquisses, de 3D et de dessins.
			</p>
			<p>Une fois votre projet d’aménagement arrêté, il vous propose tous les éléments techniques qui seront utilisés lors des travaux : dossiers de plan d’implantation côté, coupes, élévations, plan électrique.
			</p>
			<p>Il sélectionne avec vous et référence ensuite les différents matériaux qui seront utilisés lors des travaux d’aménagement : carrelage, parquet, fournitures sanitaires.
			</p>
			<p>Sur la base de ses plans, l’architecte d’intérieur vous met en relation avec un maitre d’œuvre et son réseau d’artisans, sélectionné pour vous et pour la spécificité de votre projet. L’expertise du maitre d’œuvre et sa connaissance du marché lui permettent d’obtenir un devis cohérent et étudié.
				Le maitre d’œuvre assurera alors le suivi et la coordination des travaux et supervisera pour vous l’avancement du chantier.
			</p>
			<p>Les plans fournis ne peuvent être considérés comme des plans d’exécution et ne doivent pas servir à la réalisation des ouvrages. Les différentes entreprises concernées par les travaux devront fournir leurs propres plans d’exécution pour validation auprès du MOA & MO avant l’intervention sur le chantier.</p>
		</article>	

	</section>
	<section>
		<h1>DIAGNOSTIC AVANT UN ACHAT IMMOBILIER</h1>

		<article>
			<p>L’ architecte d’intérieur visite avec vous le bien immobilier qui vous intéresse.</p>

			<p>Son regard professionnel vous guide en toute indépendance vis-à-vis de l’agent immobilier ou du propriétaire actuel.</p>

			<p>Pendant la visite, il vous communique ses impressions sur le lieu. Il vous signale les aspects essentiels à considérer pour se décider lors d’un achat immobilier : les potentialités du logement ainsi que ses éventuelles contraintes.</p>

			<p>Oralement, il souligne les aspects techniques du bien immobilier : murs porteurs, cloisons, qualité de l’isolation, état de la plomberie et des menuiseries intérieures et extérieures, réseaux de distribution (électricité, eau, gaz).</p>

			<p>Il étudie avec vous les potentialités de l’espace : éclairage naturel, possibilité d’optimisation des espaces, redistribution des pièces du logement.</p>

			<p>A la fin de la visite, il vous fait part d’une estimation budgétaire des travaux de rénovation à envisager.</p>
			</article>
		</section>
	

</main>


<?php 
include 'footer.phtml'; 
?>