<?php 
include 'header.phtml'; 
?>
<main>
	<h1>ARCHITECTURE D’INTERIEUR</h1>

	<h2>1ère étape - RDV conseils</h2>
	<p>
	A l’occasion d’une première rencontre, l’architecte d’intérieur est à votre écoute pour comprendre votre projet d’aménagement, de rénovation ou de construction. Il tient compte, non seulement de vos besoins en termes d'espaces, mais également de vos goûts (matériaux, couleurs, mobilier).
	</p>
	<p>La visite de votre logement lui permet d’évaluer le potentiel de votre intérieur et d’optimiser la surface disponible en fonction de vos besoins et votre budget.
	</p>
	<p>Son expérience et son expertise en architecture d’intérieur lui permettent de vous faire part de ses idées et de ses conseils en matière d’aménagement, de matériaux, d’équipement et d’ameublement.  
	</p>

	<h2>2ème étape - Etude de votre projet d’architecture d’intérieur</h2>
	<p>A partir du relevé de l’existant et du potentiel de votre intérieur, l’architecte d’intérieur vous fait différentes propositions d’aménagement de votre intérieur, à l’aide d’esquisses, de 3D et de dessins.
	</p>
	<p>Une fois votre projet d’aménagement arrêté, il vous propose tous les éléments techniques qui seront utilisés lors des travaux : dossiers de plan d’implantation côté, coupes, élévations, plan électrique.
	</p>
	<p>Il sélectionne avec vous et référence ensuite les différents matériaux qui seront utilisés lors des travaux d’aménagement : carrelage, parquet, fournitures sanitaires.
	</p>
	<p>Sur la base de ses plans, l’architecte d’intérieur vous met en relation avec un maitre d’œuvre et son réseau d’artisans, sélectionné pour vous et pour la spécificité de votre projet. L’expertise du maitre d’œuvre et sa connaissance du marché lui permettent d’obtenir un devis cohérent et étudié.
	Le maitre d’œuvre assurera alors le suivi et la coordination des travaux et supervisera pour vous l’avancement du chantier.
	</p>





	<h1>RELOOKING D’INTERIEUR/ COACHING DECO</h1>

	<h2>1ère étape – RDV conseils relooking	</h2>

	<p>Lors d’une première rencontre à votre domicile, l’architecte d’intérieur évalue le potentiel et l’ambiance de votre logement.</p>
	<p>
	Il s’imprègne de vos envies d’aménagement, de vos goûts en matière de décoration et de mobilier. Vous lui faites part de vos attentes aussi bien esthétiques que pratiques.
	</p>
	<p>Son expertise lui permet de vous faire part immédiatement d’idées nouvelles sur la base de votre mobilier actuel et de vos attentes.
	</p>
	<p>Un nouvel aménagement peut éventuellement être mis en place dès le premier rendez-vous, sur la base du mobilier et des objets déco que vous possédez déjà.
	</p>
	  
	<h2>2ème étape – Coach Shopping Déco</h2>
	<p>A la suite du 1er RDV Conseils déco, le relooking d’intérieur peut être complété par un coaching déco :</p>

	<p>L’architecte d’intérieur vous accompagne dans une sélection de magasins de décoration, qu’il a sélectionné en fonction de vos goûts, de vos besoins et de votre budget.</p>

	<p>Il vous oriente vers du mobilier et des objets de décoration qui viendront compléter ce que vous possédez déjà afin de rendre votre intérieur plus convivial.</p>




	<h1>DIAGNOSTIC AVANT UN ACHAT IMMOBILIER</h1>

	<p>L’ architecte d’intérieur visite avec vous le bien immobilier qui vous intéresse.</p>

	<p>Son regard professionnel vous guide en toute indépendance vis-à-vis de l’agent immobilier ou du propriétaire actuel.</p>

	<p>Pendant la visite, il vous communique ses impressions sur le lieu. Il vous signale les aspects essentiels à considérer pour se décider lors d’un achat immobilier : les potentialités du logement ainsi que ses éventuelles contraintes.</p>

	<p>Oralement, il souligne les aspects techniques du bien immobilier : murs porteurs, cloisons, qualité de l’isolation, état de la plomberie et des menuiseries intérieures et extérieures, réseaux de distribution (électricité, eau, gaz).</p>

	<p>Il étudie avec vous les potentialités de l’espace : éclairage naturel, possibilité d’optimisation des espaces, redistribution des pièces du logement.</p>

	<p>A la fin de la visite, il vous fait part d’une estimation budgétaire des travaux de rénovation à envisager.</p>



	<h1>ARCHITECTURE COMMERCIALE</h1>
	<p>L’aménagement, la rénovation ou la construction de votre espace professionnel s’appuie en amont sur une étude personnalisée qui fait le point sur votre concept, vos besoins et vos goûts.</p>
	<p>L’objectif est de proposer un aménagement qui reflète vos envies et qui répond aux besoins fonctionnels de votre espace professionnel en s’inscrivant dans l'enveloppe budgétaire.</p>
	<p>A partir des suggestions proposées par l’architecte d’intérieur et sur la base de vos observations, le projet d’aménagement commercial s’affine progressivement avant le début des travaux.</p>

	<h2>1ère étape : RDV conseils</h2>

	<p>A l’occasion d’un premier rendez-vous, vous confiez à l’architecte d’intérieur vos besoins et vos attentes concernant les travaux d’aménagement ou de rénovation de votre espace professionnel : qu’il s’agisse d’une boutique, d’un hôtel, d’un restaurant, d’un centre d’accueil du public ou des bureaux de votre entreprise.</p>

	<p>Vous lui faites part non seulement de vos goûts en matière de décoration mais également de vos attentes en termes d’organisation de l’espace. Exemple pour des bureaux : circulation des employés, collaboration entre les différents services, nécessité d’espaces de réunion, répondant à des normes de sécurité ou à des normes sanitaires (dans le cas d’un restaurant).  </p>

	<p>A partir de ces éléments, il sera en mesure de comprendre votre concept et votre projet afin de créer un espace en adéquation avec votre activité.</p>

	<p>Lors du premier rendez-vous, l’architecte évalue le potentiel des lieux, ses atouts (luminosité, possibilité d’ouverture des espaces) ainsi que ses contraintes (murs porteurs, réseaux, normes). Il vous fait part immédiatement de ses idées en termes d’aménagement et de décoration intérieure.</p>


	<h2>2ème étape - Etude de votre projet d’architecture d’intérieur</h2>
	<p>A partir du relevé de l’existant et du potentiel de votre intérieur, l’architecte d’intérieur vous fait différentes propositions d’aménagement de votre intérieur, à l’aide d’esquisses, de 3D et de dessins.</p>

	<p>Une fois votre projet d’aménagement arrêté, il vous propose tous les éléments techniques qui seront utilisés lors des travaux : dossiers de plan d’implantation côté, coupes, élévations, plan électrique.</p>

	<p>Il sélectionne avec vous et référence ensuite les différents matériaux qui seront utilisés lors des travaux d’aménagement : carrelage, parquet, fournitures sanitaires.</p>

	<p>Sur la base de ses plans, l’architecte d’intérieur vous met en relation avec un maitre d’œuvre et son réseau d’artisans, sélectionné pour vous et pour la spécificité de votre projet. L’expertise du maitre d’œuvre et sa connaissance du marché lui permettent d’obtenir un devis cohérent et étudié.
	Le maitre d’œuvre assurera alors le suivi et la coordination des travaux et supervisera pour vous l’avancement du chantier.
	</p>

</main>


<?php 
include 'footer.phtml'; 
?>