<?php 
include 'header.phtml'; 
?>
<main>
	<section>
		<h1>Rénovation intérieure</h1>
​		<article>
Agencement d'un RDC comprenant le salon et

la cuisine. 
Agencement de bureau/ bibliothèque
​

Le bureau s'impose dans la pièce par un plateau continue en bois massif. Il sert égalemnt d'accès pour récupérer les livres de la bibliothèque en partie haute.
Construction d'une maison
​

Construction d'une maison moderne s'inscrivant dans son environnement et suivant l'altimétrie du terrain afin de se fondre et d'être le mieux intégrée possible.

Accès par le niveau RDC, qui comprend les pièces de vie: salon, cuisine...

Le niveau R-1 regroupe les chambres et le niveau R+1 regroupe une chambre et la partie garage.
Rénovation d'une maison
​

Rénovation complète  d'une maison. L'agencement intérieur a été complètement revu : la cuisine, la salle de bain, le salon....
		</article>


	</section>
	<section>
		<h1>Extension d'une maison</h1>
		​

		<article>Démolition d'une partie du bâtiment existant pour créer cette extension. Lien entre l'accès côté rue et côté jardin. Pièce de transition, composée de grande verrière afin d'apporter un maximum de lumière naturelle.
		</article>

	</section>
	<section>
		<h1>Rénovation d'un Hangar</h1>
​		<article>

		Rénovation d'un hangar en habiatation sur deux niveaux.

		Au RDC, on trouve les pièces de vies: salon, cuisine, cellier, et la partie garage.

		Le R+1 est desservi par une passerelle et des escaliers permettant de passer sous la charpente et d'économiser de la place dans les pièces de vies.

		Création d'une cuisine extérieure comprenant un petit salon, sous un abri ouvert et couvert.
		</article>


	</section>

<section>

Construction d'une maison
​

Construction d'une maison neuve sur 3 niveaux. 

Le R-1 : sous-sol accessible depuis le jardin

Le RDC: salon/cuisine/chambres

Le R+1: chambres



Construction d'une maison
​

Construction d'une maison en ossature bois avec une finition en bardage horizontal.

Maison s'étendant sur 3 niveaux.

Le RDC est accessible depuis la rue, et comprend le salon/ cuisine/ cellier.

Le R-1 comprend les chambres et est accessible depuis le jardin 

Le R+1 comprend la chambre parentale.
Rénovation d'une maison
​

Rénovation et extension d'une maison afin d'agrandir la pièce de vie et d' apporter plus de lumière naturelle à la pièce.

Finition en bardage bois vertical, dans la même teinte que les clôtures, la terrasse, et l'habillage

du jacuzzi.

Le positionnement de l'extension a permis de créer un patio entre l'extension et la maison existante.
Rénovation d'une maison
​

Rénovation d'une maison s'articulant autour d'une cour intérieur.

Création d'une extension servant de passage entre la rue et la partie habitation. Cette extension est entièrement vitrée afin d'apporter un maximum de lumière naturelle.

Les façades existantes ont été entièrement modifiées. De grandes baies vitrées ainsi que de grandes verrières ont été mises en place.
Aménagement Intérieur
​

Aménagement intérieur d'une maison, autour de la cuisine principaalement.

Travail sur laa décoraation, le positionnement du mobilier, les couleurs...


Aménagement intérieur d'une maison, autour de la cuisine principaalement.

Travail sur laa décoraation, le positionnement du mobilier, les couleurs...
Construction d'une maison
​

Construction d'une maison en ossature bois avec une finition en bardage horizontal.

Maison s'étendant sur 3 niveaux.

Le RDC est accessible depuis la rue, et comprend le salon/ cuisine/ cellier.

Le R-1 comprend les chambres et est accessible depuis le jardin 

Le R+1 comprend la chambre parentale.
Construction d'une maison
​

Construction d'une maison contemporaine en bardage bois et toiture zinc.

Maison s'étendant sur 2 niveaux.

Le RDC est accessible depuis la rue, et comprend le salon/ cuisine/ bureau.

Le R-1 comprend les chambres et est accessible depuis le RDC et le jardin 

	​</section>
	<section>
Rénovation d'une maison
​

Rénovation d'une maison méditerranéenne.

A l'origine, la maison était louée pour chaque niveau, ce qui fait qu'il y avait deux salons, deux cuisines...

Création d'une nouvel agencement pour l'espace intérieur. Redistribution des pièces et créations de nouvelles

Les façades et les ouvertures existantes ont été conservées afin de ne pas enlever le cachet existant de cette maison.
Rénovation d'un appartement parisien
​

Création d'un nouvel agencement et rénovation complète de l'intérieur. 
L'espace Salon/ Séjour existant est regroupé en un seul espace pour accueillir le Salon/Cuisine. 

Le parquet existant est conservé.

Le plafond est descendu afin de rajouter une isolation acoustique à l'appartement.
L'ancienne cuisine devient la salle de bain et la salle de bain, une chambre d'amis/ Bureau.
La chambre reste à son emplacement actuel, derrière l'espace cuisine.
L'ensemble des menuiseries a été changé
Rénovation d'une maison en bord de mer, Pornic
​​

Réalisation d'un habillage de cheminée afin de la rendre plus moderne.
Changement du sol et pose d'un parquet sur le carrelage existant.
Nouvelle décoration et nouveau mobilier, accordés à du mobilier existant qui est conservé.
	</section>
	
</main>


<?php 
include 'footer.phtml'; 
?>