<?php 
include 'header.phtml'; 
?>
<main>

	<section>
		<table>
			<tr>
				<td>
					<i class="fas fa-chevron-left"></i>
				</td>
				<td colspan="15" class="center">
					<img width="700px" class="realisationPartBigOne" src="<?= $realisationPart["img1"] ?>"> 
				</td>
				<td>
					<i class="fas fa-chevron-right"></i>
				</td>
			</tr>
			<tr>
				
				<td class="grayscale center">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img1"] ?>"> 
				</td>
				<td class="grayscale center">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img2"] ?>"> </td>
				<td class="grayscale center">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img3"] ?>"></td> 
				<td class="grayscale center">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img4"] ?>"></td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img5"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img5'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img6"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img6'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img7"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img7'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img8"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img8'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img9"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img9'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img10"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img10'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img11"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img11'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img12"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img12'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img13"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img13'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img14"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img14'] ?>">
				<?php
					}
				?>
				</td>
			</tr>
			<tr>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img15"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img15'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img16"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img16'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img17"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img17'] ?>">
				<?php
					}
				?>
				</td>
				<td class="grayscale center">
				<?php 
					if ($realisationPart["img18"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPart['img18'] ?>">
				<?php
					}
				?>
				</td>
				
			
			</tr>
			<tr>
				<td colspan="17"> 
					<h5 class="name"><?= $realisationPart["name"] ?></h5>
					<p class="description"><?= $realisationPart["description"] ?></p>
					<p class="description"><?= $realisationPart["description2"] ?></p>
					<p class="description"><?= $realisationPart["description3"] ?></p>
				</td>
				
					
					
				
			</tr>

		</table>
	</section>
	

</main>

<?php 
include 'footer.phtml'; 
?>