<?php 
include 'header.phtml'; 
?>
<main>

	<section>
		<h2> Réalisations pour les professionnels </h2>
		<?php foreach (array_reverse($reaListPro) as $reaPro): ?>
		
		<article class="reaPro grayscale">
			<img src="<?= $reaPro["img1"] ?>">	
			<h5 class="name"><?= $reaPro["name"] ?></h5>
			<!-- <p class="description"><?= $reaPro["description"] ?></p> -->
			<a class ='detailButton' href = "realisationPro.php?id=<?= $reaPro["id"] ?>"> Description </a>
		</article>
		</a>
		<?php endforeach; ?>
	</section>



	

</main>

<?php 
include 'footer.phtml'; 
?>