<?php 
include 'header.phtml'; 
?>
<main class="alignCenter container">


	<section>
		<h2> Réalisations pour les professionnels </h2>
		<?php foreach (array_reverse($reaListPro) as $reaPro): ?>
		
		<article class="reaPro grayscale">
			<a href = "realisationPro.php?id=<?= $reaPro["id"] ?>"> 
			<img src="<?= $reaPro["img1"] ?>">	
			<h6 class="name"><?= $reaPro["name"] ?></h6>
			</a>
		</article>
		
		<?php endforeach; ?>
	</section>
	
</main>

<?php 
include 'footer.phtml'; 
?>