<?php 
include 'header.phtml'; 
?>
<main>
	<section>
		<h2> Réalisations pour les Particuliers </h2>
		<?php foreach (array_reverse($reaListPart) as $reaPart): ?>
		<a href = "realisationPro.php?id=<?= $reaPro["id"] ?>">		
		<article class="reaPart grayscale">
			<img src="<?= $reaPart["img1"] ?>">	
			<h6 class="name"><?= $reaPart["name"] ?></h6>
			<!-- <p class="description"><?= $reaPart["description"] ?></p> -->
			<a class ='detailButton' href = "realisationPart.php?id=<?= $reaPart["id"] ?>"> Description </a>
		</article>
		</a>
		<?php endforeach; ?>
	</section>
</main>


<?php 
include 'footer.phtml'; 
?>