<?php 
include 'header.phtml'; 
?>
<main>
	<section class="realisations">
		<h3>Réalisations</h3>
		<a href="realisationsParticuliers.php">
			<h5>Particulier</h5>
		</a>
		<a href="realisationsProfessionnels.php">
			<h5>Professionnel</h5>
		</a>
		<a href="realisationsParticuliers.php"><img src="../views/img/DSC01700.jpg" alt="particulier"></a>
	
		<a href="realisationsProfessionnels.php"><img src="../views/img/DSC03677.jpg" alt="professionnel"></a>
	</section>
</main>
<?php 
include 'footer.phtml'; 
?>