<?php 
include 'header.phtml'; 
?>
<main>

	<section>
		<h2> Réalisations pour les professionnels </h2>
		<?php foreach (array_reverse($reaListPro) as $reaPro): ?>
		<article class="reaPro">
			<img src="<?= $reaPro["img1"] ?>">	
			<p class="name"><?= $reaPro["name"] ?></p>
			<p class="description"><?= $reaPro["description"] ?></p>
			<a class ='detailButton' href = "realisationPro.php?id=<?= $reaPro["id"] ?>"> Description </a>
		</article>
		<?php endforeach; ?>
	</section>



	

</main>

<?php 
include 'footer.phtml'; 
?>