<?php 
include 'header.phtml'; 
?>
<main>
	<section>
		<h2> Réalisations pour les Particuliers </h2>
		<?php foreach (array_reverse($reaListPart) as $reaPart): ?>
		<article class="reaPart">
			<img src="<?= $reaPart["img1"] ?>">	
			<p class="name"><?= $reaPart["name"] ?></p>
			<p class="description"><?= $reaPart["description"] ?></p>
			<a class ='detailButton' href = "realisationPart.php?id=<?= $reaPart["id"] ?>"> Description </a>
		</article>
		<?php endforeach; ?>
	</section>
</main>


<?php 
include 'footer.phtml'; 
?>