<?php 
include 'header.phtml'; 
?>
<main>

	<section id="heightRea">
		<div id="diaporama">
			<!-- <div>
				<i class="fas fa-chevron-left"></i>
			</div> -->
			<div class="centre" >
				<h4 class="imageReaHover">Touchez une image miniature pour qu'elle s'agrandisse</h4>
			</div>
			<!-- <div>
				<i class="fas fa-chevron-right"></i>
			</div> -->
		
			<div class="bas" >
				
				<div class="grayscale center">
					<img class=" realisationPartImg hoverBigView" src="<?= $realisationPro["img1"] ?>"/> <img class="grande" src="<?= $realisationPro["img1"] ?>"/> 
				</div>
				<div class="grayscale center">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPro["img2"] ?>"/> 
					<img class="grande" src="<?= $realisationPro["img2"] ?>"/> 
				</div>
				<div class="grayscale center">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPro["img3"] ?>"/><img class="grande" src="<?= $realisationPro["img3"] ?>"/>
				</div> 
				<div class="grayscale center">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPro["img4"] ?>"/><img class="grande" src="<?= $realisationPro["img4"] ?>"/>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img5"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img5'] ?>"/><img class="grande" src="<?= $realisationPro['img5'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img6"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img6'] ?>"/><img class="grande" src="<?= $realisationPro['img6'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img7"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img7'] ?>"/><img class="grande" src="<?= $realisationPro['img7'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img8"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img8'] ?>"/><img class="grande" src="<?= $realisationPro['img8'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img9"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img9'] ?>"/><img class="grande" src="<?= $realisationPro['img9'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img10"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img10'] ?>"/><img class="grande" src="<?= $realisationPro['img10'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img11"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img11'] ?>"/><img class="grande" src="<?= $realisationPro['img11'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img12"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img12'] ?>"/><img class="grande" src="<?= $realisationPro['img12'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img13"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img13'] ?>"/><img class="grande" src="<?= $realisationPro['img13'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img14"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img14'] ?>"/><img class="grande" src="<?= $realisationPro['img14'] ?>"/>
				<?php
					}
				?>
				</div>
			
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img15"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img15'] ?>"/><img class="grande" src="<?= $realisationPro['img15'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img16"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img16'] ?>"/><img class="grande" src="<?= $realisationPro['img16'] ?>"/>
				<?php
					}
				?>
				</div>
				<div class="grayscale center">
				<?php 
					if ($realisationPro["img17"]!= null){
				?>
						<img class="realisationPartImg hoverBigView" src="<?= $realisationPro['img17'] ?>"/><img class="grande" src="<?= $realisationPro['img17'] ?>"/>
				<?php
					}
				?>
				</div>
				
				
			</div>


			<div > 
				<h5 class="name"><?= $realisationPro["name"] ?></h5>
				<p class="description"><?= $realisationPro["description"] ?></p>
				<p class="description"><?= $realisationPro["description2"] ?></p>
				<p class="description"><?= $realisationPro["description3"] ?></p>
			</div>
			<div class="clear"></div>
		
		</div>
	
	</section>
	

</main>


<?php 
include 'footer.phtml'; 
?>