<?php 
include 'header.phtml'; 
?>
<main>

	<section>
		<table>
			<tr>
				<td colspan="17"> 
					<img class="realisationProBigOne" src="<?= $realisationPro["img1"] ?>"> 
				</td>
			</tr>
			<tr>
				<td colspan="17">
					<h5 class="name"><?= $realisationPro["name"] ?></h5>
					<p class="productPrice"><?= $realisationPro["description"] ?></p>
					
				</td>
			</tr>
			<tr>
				<td class="grayscale">
					<img class="realisationProImg" src="<?= $realisationPro["img1"] ?>"> 
				</td>
				<td class="grayscale">
					<img class="realisationProImg" src="<?= $realisationPro["img2"] ?>"> </td>
				<td class="grayscale">
					<img class="realisationProImg" src="<?= $realisationPro["img3"] ?>"></td> 
				<td class="grayscale">
					<img class="realisationProImg" src="<?= $realisationPro["img4"] ?>"></td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img5"] ?>"> </td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img6"] ?>"> </td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img7"] ?>"> </td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img8"] ?>"> </td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img9"] ?>"> </td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img10"] ?>"></td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img11"] ?>"></td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img12"] ?>"></td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img13"] ?>"> </td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img14"] ?>"></td>
			</tr>
			<tr>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img15"] ?>"> </td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img16"] ?>"> </td>
				<td class="grayscale"><img class="realisationProImg" src="<?= $realisationPro["img17"] ?>"> </td>
			
				
			</tr>
		</table>
	</section>
	

</main>

<?php 
include 'footer.phtml'; 
?>