<?php 
include 'header.phtml'; 
?>
<main class="container">
	<section class="realisations">
		<h3>Réalisations</h3>
		<article class="realisationsParticuliers">
			<a href="realisationsParticuliers.php">
				<img src="../views/img/DSC01700.jpg" alt="particulier">
				<h5>Particuliers</h5>
			</a>
		</article>
		<article class="realisationsProfessionnels">
			<a href="realisationsProfessionnels.php">
				<img src="../views/img/DSC03677.jpg" alt="professionnel">
				<h5>Professionnels</h5>
			</a>
		</article>


	</section>
</main>
<?php 
include 'footer.phtml'; 
?>