<?php 
include 'header.phtml'; 
?>
<main class="container"> 
	<section>	
	 <!-- Slideshow container -->
		<div class="slideshow-container">

		  <!-- Full-width images with number and caption text -->
		  <div class="mySlides fade center">
		    <div class="numbertext"></div>
		    <img class="center" src="<?= $realisationPart["img1"] ?>"/>
		    <div class="text"></div>
		  </div>

		  <div class="mySlides fade center">
		    <div class="numbertext"></div>
		    <img class="center" src="<?= $realisationPart["img2"] ?>"/>
		    <div class="text"></div>
		  </div>

		  <div class="mySlides fade center">
		    <div class="numbertext"></div>
		     <img src="<?= $realisationPart["img3"] ?>"/>
		    <div class="text"></div>
		  </div>
  		 
		  <div class="mySlides fade center">
		    <div class="numbertext"></div>
		     <img src="<?= $realisationPart["img4"] ?>"/>
		    <div class="text"></div>
		  </div>
	  	<?php 
			if ($realisationPart["img5"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img5"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img6"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img6"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img7"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img7"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img8"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img8"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img9"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img9"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img10"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img10"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img11"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img11"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img12"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img12"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img13"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img13"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img14"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img14"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img15"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img15"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img16"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img16"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img17"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img17"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img18"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPart["img18"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>

		  <!-- Next and previous buttons -->
		  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
		  <a class="next" onclick="plusSlides(1)">&#10095;</a>
		</div>
		<br>

		<!-- The dots/circles -->
		<div style="text-align:center">
		  <span class="dot" onclick="currentSlide(1)"></span>
		  <span class="dot" onclick="currentSlide(2)"></span>
		  <span class="dot" onclick="currentSlide(3)"></span>
		  <span class="dot" onclick="currentSlide(4)"></span>
		  <?php 
			if ($realisationPart["img5"]!= null){
		?>
			<span class="dot" onclick="currentSlide(5)"></span>
		<?php
			}
		?>
		  <?php 
			if ($realisationPart["img6"]!= null){
		?>
			<span class="dot" onclick="currentSlide(6)"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img7"]!= null){
		?>
			<span class="dot" onclick="currentSlide(7)"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img8"]!= null){
		?>
			<span class="dot" onclick="currentSlide(8)"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img9"]!= null){
		?>
			<span class="dot" onclick="currentSlide(9)"></span>
		<?php
			}
		?>
		 <?php 
			if ($realisationPart["img10"]!= null){
		?>
			<span class="dot" onclick="currentSlide(10)"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img11"]!= null){
		?>
			<span class="dot" onclick="currentSlide(11)"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img12"]!= null){
		?>
			<span class="dot" onclick="currentSlide(12)"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img13"]!= null){
		?>
			<span class="dot" onclick="currentSlide(13)"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img14"]!= null){
		?>
			<span class="dot" onclick="currentSlide(14)"></span>
		<?php
			}
		?>
		 <?php 
			if ($realisationPart["img15"]!= null){
		?>
			<span class="dot" onclick="currentSlide(15)"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img16"]!= null){
		?>
			<span class="dot" onclick="currentSlide(16)"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPart["img17"]!= null){
		?>
			<span class="dot" onclick="currentSlide(17)"></span>
		<?php
			}
		?>
		 <?php 
			if ($realisationPart["img18"]!= null){
		?>
			<span class="dot" onclick="currentSlide(18)"></span>
		<?php
			}
		?>
		  
		</div> 

		<div > 
			<h5 class="name"><?= $realisationPart["name"] ?></h5>
			<p class="description"><?= $realisationPart["description"] ?></p>
			<p class="description"><?= $realisationPart["description2"] ?></p>
			<p class="description"><?= $realisationPart["description3"] ?></p>
		</div>
	</section>
</main>
<?php 
include 'footer.phtml'; 
?>