<?php 
include 'header.phtml'; 
?>
<main class="container"> 
	<section>	
	 <!-- Slideshow container -->
		<div class="slideshow-container">

		  <!-- Full-width images with number and caption text -->
		  <div class="mySlides fade center">
		    <div class="numbertext">1 / 3</div>
		    <img class="center" src="<?= $realisationPart["img1"] ?>"/>
		    <div class="text">Caption Text</div>
		  </div>

		  <div class="mySlides fade center">
		    <div class="numbertext">2 / 3</div>
		    <img class="center" src="<?= $realisationPart["img2"] ?>"/>
		    <div class="text">Caption Two</div>
		  </div>

		  <div class="mySlides fade center">
		    <div class="numbertext">3 / 3</div>
		     <img src="<?= $realisationPart["img3"] ?>"/>
		    <div class="text">Caption Three</div>
		  </div>

		  <!-- Next and previous buttons -->
		  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
		  <a class="next" onclick="plusSlides(1)">&#10095;</a>
		</div>
		<br>

		<!-- The dots/circles -->
		<div style="text-align:center">
		  <span class="dot" onclick="currentSlide(1)"></span>
		  <span class="dot" onclick="currentSlide(2)"></span>
		  <span class="dot" onclick="currentSlide(3)"></span>
		</div> 
	</section>
</main>
<?php 
include 'footer.phtml'; 
?>