<?php 
include 'header.phtml'; 
?>
<main class="container"> 
	<section>	
	 <!-- Slideshow container -->
		<div class="slideshow-container">

		  <!-- Full-width images with number and caption text -->
		  <div class="mySlides fade center">
		    <div class="numbertext"></div>
		    <img class="center" src="<?= $realisationPro["img1"] ?>"/>
		    <div class="text"></div>
		  </div>

		  <div class="mySlides fade center">
		    <div class="numbertext"></div>
		    <img class="center" src="<?= $realisationPro["img2"] ?>"/>
		    <div class="text"></div>
		  </div>

		  <div class="mySlides fade center">
		    <div class="numbertext"></div>
		     <img src="<?= $realisationPro["img3"] ?>"/>
		    <div class="text"></div>
		  </div>
  		 
		  <div class="mySlides fade center">
		    <div class="numbertext"></div>
		     <img src="<?= $realisationPro["img4"] ?>"/>
		    <div class="text"></div>
		  </div>
	  	<?php 
			if ($realisationPro["img5"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img5"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img6"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img6"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img7"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img7"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img8"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img8"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img9"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img9"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img10"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img10"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img11"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img11"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img12"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img12"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img13"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img13"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img14"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img14"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img15"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img15"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img16"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img16"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img17"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img17"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img18"]!= null){
		?>
			<div class="mySlides fade center">
		   		<div class="numbertext"></div>
		   	  	<img src="<?= $realisationPro["img18"] ?>"/>
		    	<div class="text"></div>
		  	</div>
		<?php
			}
		?>

		  <!-- Next and previous buttons -->
			<a id="prev" >&#10094;</a>
			<a id="next" >&#10095;</a>
		</div>

		<!-- The dots/circles -->
		<div style="text-align:center">
		  <span class="dot" id="dot1"></span>
		  <span class="dot" id="dot2"></span>
		  <span class="dot" id="dot3"></span>
		  <span class="dot" id="dot4"></span>
		  <?php 
			if ($realisationPro["img5"]!= null){
		?>
			<span class="dot" id="dot5"></span>
		<?php
			}
		?>
		  <?php 
			if ($realisationPro["img6"]!= null){
		?>
			<span class="dot" id="dot6"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img7"]!= null){
		?>
			<span class="dot" id="dot7"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img8"]!= null){
		?>
			<span class="dot" id="dot8"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img9"]!= null){
		?>
			<span class="dot" id="dot9"></span>
		<?php
			}
		?>
		 <?php 
			if ($realisationPro["img10"]!= null){
		?>
			<span class="dot" id="dot10"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img11"]!= null){
		?>
			<span class="dot" id="dot11"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img12"]!= null){
		?>
			<span class="dot" id="dot12"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img13"]!= null){
		?>
			<span class="dot" id="dot13"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img14"]!= null){
		?>
			<span class="dot" id="dot14"></span>
		<?php
			}
		?>
		 <?php 
			if ($realisationPro["img15"]!= null){
		?>
			<span class="dot" id="dot15"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img16"]!= null){
		?>
			<span class="dot" id="dot16"></span>
		<?php
			}
		?>
		<?php 
			if ($realisationPro["img17"]!= null){
		?>
			<span class="dot" id="dot17"></span>
		<?php
			}
		?>
		 <?php 
			if ($realisationPro["img18"]!= null){
		?>
			<span class="dot" id="dot18"></span>
		<?php
			}
		?>
		  
		</div> 

		<div > 
			<h5 class="name"><?= $realisationPro["name"] ?></h5>
			<p class="description"><?= $realisationPro["description"] ?></p>
			<p class="description"><?= $realisationPro["description2"] ?></p>
			<p class="description"><?= $realisationPro["description3"] ?></p>
		</div>
	</section>
</main>
<?php 
include 'footer.phtml'; 
?>