<?php 
include 'header.phtml'; 
?>
<main>

	<section>
		<table>
			<tr>
				<td colspan="17"> 
					<img class="realisationPartBigOne" src="<?= $realisationPart["img1"] ?>"> 
				</td>
			</tr>
			<tr>
				<td>
					<i class="fas fa-chevron-left"></i>
				</td>
				<td class="grayscale">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img1"] ?>"> 
				</td>
				<td class="grayscale">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img2"] ?>"> </td>
				<td class="grayscale">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img3"] ?>"></td> 
				<td class="grayscale">
					<img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img4"] ?>"></td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img5"] ?>"> </td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img6"] ?>"> </td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img7"] ?>"> </td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img8"] ?>"> </td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img9"] ?>"> </td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img10"] ?>"></td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img11"] ?>"></td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img12"] ?>"></td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img13"] ?>"> </td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img14"] ?>"></td>
			</tr>
			<tr>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img15"] ?>"> </td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img16"] ?>"> </td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img17"] ?>"> </td>
				<td class="grayscale"><img class="realisationPartImg hoverBigView" src="<?= $realisationPart["img18"] ?>"> </td>
				<td>
					<i class="fas fa-chevron-right"></i>
				</td>
			
			</tr>
			<tr>
				<td colspan="17"> 
					<p class="name"><?= $realisationPart["name"] ?></p>
					<p class="description"><?= $realisationPart["description"] ?></p>
					<p class="description"><?= $realisationPart["description2"] ?></p>
					<p class="description"><?= $realisationPart["description3"] ?></p>
				</td>
				
					
					
				
			</tr>

		</table>
	</section>
	

</main>

<?php 
include 'footer.phtml'; 
?>